pizzerona/Controllers/BIBITEsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using pizzerona.Models;

namespace pizzerona.Controllers
{
    [Authorize(Roles = "Admin")]
    public class BIBITEsController : Controller
    {
        private Model1 db = new Model1();

        // GET: BIBITEs
        public ActionResult Index()
        {
            return View(db.BIBITE.ToList());
        }

        // GET: BIBITEs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BIBITE bIBITE = db.BIBITE.Find(id);
            if (bIBITE == null)
            {
                return HttpNotFound();
            }
            return View(bIBITE);
        }

        // GET: BIBITEs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BIBITEs/Create
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_BIBITA,NOME,IMG,PREZZO")] BIBITE bIBITE)
        {
            if (ModelState.IsValid)
            {
                db.BIBITE.Add(bIBITE);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(bIBITE);
        }

        // GET: BIBITEs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BIBITE bIBITE = db.BIBITE.Find(id);
            if (bIBITE == null)
            {
                return HttpNotFound();
            }
            return View(bIBITE);
        }

        // POST: BIBITEs/Edit/5
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_BIBITA,NOME,IMG,PREZZO")] BIBITE bIBITE)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bIBITE).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(bIBITE);
        }

        // GET: BIBITEs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BIBITE bIBITE = db.BIBITE.Find(id);
            if (bIBITE == null)
            {
                return HttpNotFound();
            }
            return View(bIBITE);
        }

        // POST: BIBITEs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BIBITE bIBITE = db.BIBITE.Find(id);
            db.BIBITE.Remove(bIBITE);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

pizzerona/Controllers/CLIENTEsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using pizzerona.Models;

namespace pizzerona.Controllers
{
    public class CLIENTEsController : Controller
    {
        private Model1 db = new Model1();

        // GET: CLIENTEs

        // nuovo
        public ActionResult Index()
        {
            return View(db.CLIENTE.ToList());
        }

        // GET: CLIENTEs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CLIENTE cLIENTE = db.CLIENTE.Find(id);
            if (cLIENTE == null)
            {
                return HttpNotFound();
            }
            return View(cLIENTE);
        }

        // GET: CLIENTEs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CLIENTEs/Create
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_CLIENTE,NOME,COGNOME,INDIRIZZO,CITTA,CAP,RUOLO,EMAIL,PASSWORD")] CLIENTE cLIENTE)
        {
            if (ModelState.IsValid)
            {
                db.CLIENTE.Add(cLIENTE);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cLIENTE);
        }

        // GET: CLIENTEs/Login
        public ActionResult Login( CLIENTE model)
        {
          
                var user = db.CLIENTE.FirstOrDefault(u => u.EMAIL.Equals(model.EMAIL) && u.PASSWORD.Equals(model.PASSWORD));
               



                if (user != null)
                {
                // conservo IL RUOLO e il cookie con l'ID_CLIENTE

                FormsAuthentication.SetAuthCookie(user.ID_CLIENTE.ToString(), false);

                HttpCookie LoginCookie = new HttpCookie("IDCookie");

                LoginCookie.Value = user.ID_CLIENTE.ToString();

                LoginCookie.Expires = DateTime.Now.AddHours(1);

                Response.Cookies.Add(LoginCookie);

                return RedirectToAction("Index","Home");

                }
                else
                {
                    ModelState.AddModelError("", "Email o Password errati");
                }
            

            return View();
        }   

        // GET: CLIENTEs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CLIENTE cLIENTE = db.CLIENTE.Find(id);
            if (cLIENTE == null)
            {
                return HttpNotFound();
            }
            return View(cLIENTE);
        }

        // POST: CLIENTEs/Edit/5
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_CLIENTE,NOME,COGNOME,INDIRIZZO,CITTA,CAP,RUOLO,EMAIL,PASSWORD")] CLIENTE cLIENTE)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cLIENTE).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cLIENTE);
        }

        // GET: CLIENTEs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CLIENTE cLIENTE = db.CLIENTE.Find(id);
            if (cLIENTE == null)
            {
                return HttpNotFound();
            }
            return View(cLIENTE);
        }

        // POST: CLIENTEs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CLIENTE cLIENTE = db.CLIENTE.Find(id);
            db.CLIENTE.Remove(cLIENTE);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

pizzerona/Controllers/PizzesController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Entity;

using System.IO;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using pizzerona.Models;

namespace pizzerona.Controllers
{
   // [Authorize(Roles="Admin")]
    public class PizzesController : Controller
    {
     
        private Model1 db = new Model1();

        // GET: Pizzes
        [Authorize(Roles = "User")]
        public ActionResult Index()
        {

        //   var ordiniCliente = db.ORDINE.Where(o => o.FK_ID_CLIENTE == idCliente).Include(o => o.Pizze);
        
          //  System.Diagnostics.Debug.WriteLine($"SONO IL VALORE DI ORDINI: {PIZO}");

            return View(db.Pizze.ToList());
        }

        // GET: Pizzes/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int? id)

        {


            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pizze pizze = db.Pizze.Find(id);
            if (pizze == null)
            {
                return HttpNotFound();
            }
            return View(pizze);
        }

        // GET: Pizzes/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Pizzes/Create
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "id_Pizza,Nome,img,Prezzo,TempoConsegna,Ingredienti")] Pizze pizze, HttpPostedFileBase img )
        {


            if (img != null && img.ContentLength > 0)
            {
                string nomeFile = Path.GetFileName(img.FileName);
                string pathToSave = Path.Combine(Server.MapPath("~/img/"), nomeFile);
                img.SaveAs(pathToSave);
                pizze.img = "/img/" + nomeFile;
            }

            if (ModelState.IsValid)
            {
                db.Pizze.Add(pizze);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(pizze);
        }

        // GET: Pizzes/Edit/5

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest); // un writeline non hai scelto niente
            }
            var pizze = db.Pizze.Find(id);
      

            if (pizze == null)
            {
                return HttpNotFound();
            }
            return View("Edit", pizze);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "id_Pizza,Nome,img,Prezzo,TempoConsegna,Ingredienti")] Pizze pizze)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pizze).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pizze);
        }



        // COMES SE NON ENTRASSE
      

        [HttpGet]
        public ActionResult AddPizza(int? id)
        {
            if (id == null)
            {
                System.Diagnostics.Debug.WriteLine($"Valore di id nullo");
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }


            HttpCookie PizzaCookie = new HttpCookie("PizzaCookie");           
            PizzaCookie.Value = $"{id }"; 
            PizzaCookie.Expires = DateTime.Now.AddHours(1);
            Response.Cookies.Add(PizzaCookie);

            Pizze pizze = db.Pizze.Find(id);

            // Verifica se la pizza esiste nel database
            if (pizze == null)
            {
                
                return HttpNotFound();
            }
            // NELLE VIEW LIST RICORDARSI SEMPRE DI PASSARE UNA LISTA!!!!
            return View(new List<Pizze> { pizze });


        }


        //[HttpPost]
        //public ActionResult Add()
        //{

        //        var cookieValue = HttpContext.Request.Cookies["IDCookie"]?.Value;
        //        var cookiepizz = HttpContext.Request.Cookies["PizzaCookie"]?.Value;

        //    using (Model1 dbContext = new Model1())
        //    {
        //        db.ORDINE.Add(new ORDINE
        //            {
        //                FK_ID_PIZZA = Convert.ToInt32(cookiepizz),
        //                FK_ID_CLIENTE = Convert.ToInt32(cookieValue),
        //                INDIRIZZO_CONSEGNA = "Via Roma 1",
        //                QUANTITA = 1,
        //                TOTALE = 5,
        //                NOTA = "Nessuna nota"

        //            } );


        //        dbContext.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //}

        //[HttpPost]
        //public ActionResult AddPizza()
        //{

        //    System.Diagnostics.Debug.WriteLine($"SONO IL TUO AGGIUNGI");

        //    using (var dbContext = new Model1())
        //    {

        //        //  var cookieValue = HttpContext.Request.Cookies["PizzaCookie"]?.Value;

        //        //  System.Diagnostics.Debug.WriteLine($"SONO IL VALORE DI NUOVOORDINE: {cookieValue}");
        //        //   var cookieValue = HttpContext.Request.Cookies["PizzaCookie"]?.Value;

        //        ORDINE NuovoOrdine = new ORDINE()
        //        {
        //            FK_ID_PIZZA = Convert.ToInt32(Request.Cookies["PizzaCookie"].Value),

        //        };

        //        // Aggiunta del nuovo ordine al set di entità ORDINE
        //        dbContext.ORDINE.Add(NuovoOrdine);
        //        dbContext.SaveChanges();

        //        // Applicazione delle modifiche al database

        //    }



        //    return View("Index");
        //}




        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pizze pizze = db.Pizze.Find(id);
            if (pizze == null)
            {
                return HttpNotFound();
            }
            return View(pizze);
        }

        // POST: Pizzes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Pizze pizze = db.Pizze.Find(id);
            db.Pizze.Remove(pizze);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

pizzerona/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title - Applicazione ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-warning bellaNav">
        <div class="container">
            @Html.ActionLink("PIZZERONA", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Attiva/Disattiva spostamento" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>

                    <li>@Html.ActionLink("+Pizza", "Create", "Pizzes", new { area = "" }, new { @class = "nav-link link-dark  bg-light" })</li>
                    <li>@Html.ActionLink("+Bibita", "Create", "BIBITEs", new { area = "" }, new { @class = "nav-link link-dark ms-3 bg-light" })</li>
                    <li>@Html.ActionLink("Iscriviti", "Create", "CLIENTEs", new { area = "" }, new { @class = "nav-link link-dark ms-3 bg-light" })</li>
                    <li>@Html.ActionLink("Log in", "Login", "CLIENTEs", new { area = "" }, new { @class = "nav-link link-dark ms-3 bg-light" })</li>
                    <li>@Html.ActionLink("Carrello", "AggiungiAlCarrello", "ORDINEs", new { area = "" }, new { @class = "nav-link link-dark ms-3 bg-light" })</li>
                    <li>@Html.ActionLink("Gestione Ordini", "Index", "ORDINEs", new { area = "" }, new { @class = "nav-link link-dark ms-3 bg-light" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <footer>
                <div class="container text-light bg-black">
                    <div class="row">
                        <div class="col-md-4">
                            <h4>Contattaci</h4>
                            <p>Email: info@example.com</p>
                            <p>Telefono: +123 456 7890</p>
                        </div>
                        <div class="col-md-4">
                            <h4>Seguici</h4>
                            <p>Seguici su social media per rimanere aggiornato sulle ultime novità.</p>
                            <ul class="social-icons">
                                <li><a href="#" target="_blank"><i class="fab fa-facebook"></i></a></li>
                                <li><a href="#" target="_blank"><i class="fab fa-twitter"></i></a></li>
                                <li><a href="#" target="_blank"><i class="fab fa-instagram"></i></a></li>
                            </ul>
                        </div>
                        <div class="col-md-4">
                            <h4>Indirizzo</h4>
                            <p>Via Example, 123</p>
                            <p>Città, CAP 12345</p>
                        </div>
                    </div>
                </div>
                <div class="bottom-footer">
                    <p>&copy; 2024 Nome della tua azienda. Tutti i diritti riservati.</p>
                </div>
            </footer>




            <p>&copy; @DateTime.Now.Year - Applicazione ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>