pizzerona/Controllers/ORDINEsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using pizzerona.Models;

namespace pizzerona.Controllers
{
    public class ORDINEsController : Controller
    {
        private Model1 db = new Model1();

        //GET: ORDINEs
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var Acquisti = db.ORDINE.Where(o => o.NOTA == "Acquistato").ToList();

            return View(Acquisti.ToList());
        }



        public ActionResult Evaso(int id)
        {
            var cookieValue = HttpContext.Request.Cookies["IDCookie"]?.Value;
            int idCliente = Convert.ToInt32(cookieValue);

            // Trova l'ordine dell'ID specificato per il cliente corrente
            var ordine = db.ORDINE.FirstOrDefault(o => o.ID_ORDINE == id && o.FK_ID_CLIENTE == idCliente);

           
                // Modifica lo stato dell'ordine
                ordine.NOTA = "Evaso";

                // Salva le modifiche nel database
                db.SaveChanges();


            // Ritorna alla vista precedente o ad un'altra vista
            return View(ordine);
        }

      
        [HttpPost]
        public ActionResult AggiungiAlCarrello(int idPizza, string quantita)
        {

            int quantitaInt = Convert.ToInt32(quantita);
            // Recupera la pizza dal database utilizzando l'ID
            var pizza = db.Pizze.FirstOrDefault(p => p.id_Pizza == idPizza);

            var prezzoPizza = db.Pizze.Where(p => p.id_Pizza == idPizza)
                              .Select(prodotto => prodotto.Prezzo)
                              .FirstOrDefault();
            int prezzoInt = Convert.ToInt32(prezzoPizza);
            int totale = prezzoInt * quantitaInt;


            var cookieValue = HttpContext.Request.Cookies["IDCookie"]?.Value;
                int IDCOOKIE = Convert.ToInt32(cookieValue);
            var indizzo = db.CLIENTE.FirstOrDefault(c => c.ID_CLIENTE == IDCOOKIE);

            if (pizza != null)
            {
                // Aggiungi la pizza al carrello
                var elementoOrdine = new ORDINE {FK_ID_CLIENTE= IDCOOKIE, FK_ID_PIZZA = idPizza, QUANTITA = quantitaInt, INDIRIZZO_CONSEGNA= "via IPPOLITO" , NOTA="In corso", TOTALE = totale }; // Puoi personalizzare la quantità in base alle tue esigenze
                db.ORDINE.Add(elementoOrdine);
                db.SaveChanges();// Ritorna un'esito positivo o un messaggio di successo, a seconda delle tue esigenze
               
            }

          
            return RedirectToAction("Index","Pizze");
        }


        // tornare a fare la vista con la classe dettagli  di ordine /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// STEP 2
        [Authorize(Roles = "User")]
        public ActionResult AggiungiAlCarrello()
        {
            var cookieValue = HttpContext.Request.Cookies["IDCookie"]?.Value;
            int IDCOOKIE = Convert.ToInt32(cookieValue);
            int idCLiente = IDCOOKIE;
            System.Diagnostics.Debug.WriteLine($"SONO CLIENTE == N :{idCLiente}");

            // Seleziona gli ordini in base all'ID del cliente
            var ordini = db.ORDINE.Where(o => o.FK_ID_CLIENTE == idCLiente).ToList();

            var totale = ordini.Sum(o => o.TOTALE);
            ViewBag.Totale = totale;


            return View(ordini);
        }
        [Authorize(Roles = "User")]
        public ActionResult ModificaStato()
        {
            var cookieValue = HttpContext.Request.Cookies["IDCookie"]?.Value;
            int IDCOOKIE = Convert.ToInt32(cookieValue);
            int idCliente = IDCOOKIE;

            // Trova l'ordine relativo al cliente
            var ordini = db.ORDINE.Where(o => o.FK_ID_CLIENTE == idCliente).ToList();

            // Modifica la proprietà NOTA per ciascun ordine
            foreach (var ordine in ordini)
            {
                ordine.NOTA = "Acquistato";
            }

            // Salva le modifiche nel database
            db.SaveChanges();

            return RedirectToAction("AggiungiAlCarrello");
        }


        [Authorize(Roles = "Admin")]
        // GET: ORDINEs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ORDINE oRDINE = db.ORDINE.Find(id);
            if (oRDINE == null)
            {
                return HttpNotFound();
            }
            return View(oRDINE);
        }

        // GET: ORDINEs/Create
        public ActionResult Create()
        {
            ViewBag.FK_ID_BIBITA = new SelectList(db.BIBITE, "ID_BIBITA", "NOME");
            ViewBag.FK_ID_CLIENTE = new SelectList(db.CLIENTE, "ID_CLIENTE", "NOME");
            ViewBag.FK_ID_PIZZA = new SelectList(db.Pizze, "id_Pizza", "Nome");
            return View();
        }



        // POST: ORDINEs/Create
       
   
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "ID_ORDINE,FK_ID_PIZZA,FK_ID_BIBITA,FK_ID_CLIENTE,INDIRIZZO_CONSEGNA,QUANTITA,NOTA,TOTALE")] ORDINE oRDINE)
        {
            if (ModelState.IsValid)
            {
                db.ORDINE.Add(oRDINE);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.FK_ID_BIBITA = new SelectList(db.BIBITE, "ID_BIBITA", "NOME", oRDINE.FK_ID_BIBITA);
            ViewBag.FK_ID_CLIENTE = new SelectList(db.CLIENTE, "ID_CLIENTE", "NOME", oRDINE.FK_ID_CLIENTE);
            ViewBag.FK_ID_PIZZA = new SelectList(db.Pizze, "id_Pizza", "Nome", oRDINE.FK_ID_PIZZA);
            return View(oRDINE);
        }

        // GET: ORDINEs/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ORDINE oRDINE = db.ORDINE.Find(id);
            if (oRDINE == null)
            {
                return HttpNotFound();
            }
            ViewBag.FK_ID_BIBITA = new SelectList(db.BIBITE, "ID_BIBITA", "NOME", oRDINE.FK_ID_BIBITA);
            ViewBag.FK_ID_CLIENTE = new SelectList(db.CLIENTE, "ID_CLIENTE", "NOME", oRDINE.FK_ID_CLIENTE);
            ViewBag.FK_ID_PIZZA = new SelectList(db.Pizze, "id_Pizza", "Nome", oRDINE.FK_ID_PIZZA);
            return View(oRDINE);
        }

        // POST: ORDINEs/Edit/5
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "ID_ORDINE,FK_ID_PIZZA,FK_ID_BIBITA,FK_ID_CLIENTE,INDIRIZZO_CONSEGNA,QUANTITA,NOTA,TOTALE")] ORDINE oRDINE)
        {
            if (ModelState.IsValid)
            {
                db.Entry(oRDINE).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FK_ID_BIBITA = new SelectList(db.BIBITE, "ID_BIBITA", "NOME", oRDINE.FK_ID_BIBITA);
            ViewBag.FK_ID_CLIENTE = new SelectList(db.CLIENTE, "ID_CLIENTE", "NOME", oRDINE.FK_ID_CLIENTE);
            ViewBag.FK_ID_PIZZA = new SelectList(db.Pizze, "id_Pizza", "Nome", oRDINE.FK_ID_PIZZA);
            return View(oRDINE);
        }

        // GET: ORDINEs/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ORDINE oRDINE = db.ORDINE.Find(id);
            if (oRDINE == null)
            {
                return HttpNotFound();
            }
            return View(oRDINE);
        }

        // POST: ORDINEs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ORDINE oRDINE = db.ORDINE.Find(id);
            db.ORDINE.Remove(oRDINE);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

pizzerona/Controllers/PizzesController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Entity;

using System.IO;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using pizzerona.Models;

namespace pizzerona.Controllers
{
   // [Authorize(Roles="Admin")]
    public class PizzesController : Controller
    {
     
        private Model1 db = new Model1();

        // GET: Pizzes
        [Authorize(Roles = "User")]
        public ActionResult Index()
        {

        //   var ordiniCliente = db.ORDINE.Where(o => o.FK_ID_CLIENTE == idCliente).Include(o => o.Pizze);
        
          //  System.Diagnostics.Debug.WriteLine($"SONO IL VALORE DI ORDINI: {PIZO}");

            return View(db.Pizze.ToList());
        }

        // GET: Pizzes/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int? id)

        {


            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pizze pizze = db.Pizze.Find(id);
            if (pizze == null)
            {
                return HttpNotFound();
            }
            return View(pizze);
        }

        // GET: Pizzes/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Pizzes/Create
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "id_Pizza,Nome,img,Prezzo,TempoConsegna,Ingredienti")] Pizze pizze, HttpPostedFileBase img )
        {


            if (img != null && img.ContentLength > 0)
            {
                string nomeFile = Path.GetFileName(img.FileName);
                string pathToSave = Path.Combine(Server.MapPath("~/img/"), nomeFile);
                img.SaveAs(pathToSave);
                pizze.img = "/img/" + nomeFile;
            }

            if (ModelState.IsValid)
            {
                db.Pizze.Add(pizze);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(pizze);
        }

        // GET: Pizzes/Edit/5

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest); // un writeline non hai scelto niente
            }
            var pizze = db.Pizze.Find(id);
      

            if (pizze == null)
            {
                return HttpNotFound();
            }
            return View("Edit", pizze);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "id_Pizza,Nome,img,Prezzo,TempoConsegna,Ingredienti")] Pizze pizze)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pizze).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pizze);
        }



        // COMES SE NON ENTRASSE
      

        [HttpGet]
        public ActionResult AddPizza(int? id)
        {
            if (id == null)
            {
                System.Diagnostics.Debug.WriteLine($"Valore di id nullo");
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }


            HttpCookie PizzaCookie = new HttpCookie("PizzaCookie");           
            PizzaCookie.Value = $"{id }"; 
            PizzaCookie.Expires = DateTime.Now.AddHours(1);
            Response.Cookies.Add(PizzaCookie);

            Pizze pizze = db.Pizze.Find(id);

            // Verifica se la pizza esiste nel database
            if (pizze == null)
            {
                
                return HttpNotFound();
            }
            // NELLE VIEW LIST RICORDARSI SEMPRE DI PASSARE UNA LISTA!!!!
            return View(new List<Pizze> { pizze });


        }


        //[HttpPost]
        //public ActionResult Add()
        //{

        //        var cookieValue = HttpContext.Request.Cookies["IDCookie"]?.Value;
        //        var cookiepizz = HttpContext.Request.Cookies["PizzaCookie"]?.Value;

        //    using (Model1 dbContext = new Model1())
        //    {
        //        db.ORDINE.Add(new ORDINE
        //            {
        //                FK_ID_PIZZA = Convert.ToInt32(cookiepizz),
        //                FK_ID_CLIENTE = Convert.ToInt32(cookieValue),
        //                INDIRIZZO_CONSEGNA = "Via Roma 1",
        //                QUANTITA = 1,
        //                TOTALE = 5,
        //                NOTA = "Nessuna nota"

        //            } );


        //        dbContext.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //}

        //[HttpPost]
        //public ActionResult AddPizza()
        //{

        //    System.Diagnostics.Debug.WriteLine($"SONO IL TUO AGGIUNGI");

        //    using (var dbContext = new Model1())
        //    {

        //        //  var cookieValue = HttpContext.Request.Cookies["PizzaCookie"]?.Value;

        //        //  System.Diagnostics.Debug.WriteLine($"SONO IL VALORE DI NUOVOORDINE: {cookieValue}");
        //        //   var cookieValue = HttpContext.Request.Cookies["PizzaCookie"]?.Value;

        //        ORDINE NuovoOrdine = new ORDINE()
        //        {
        //            FK_ID_PIZZA = Convert.ToInt32(Request.Cookies["PizzaCookie"].Value),

        //        };

        //        // Aggiunta del nuovo ordine al set di entità ORDINE
        //        dbContext.ORDINE.Add(NuovoOrdine);
        //        dbContext.SaveChanges();

        //        // Applicazione delle modifiche al database

        //    }



        //    return View("Index");
        //}




        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pizze pizze = db.Pizze.Find(id);
            if (pizze == null)
            {
                return HttpNotFound();
            }
            return View(pizze);
        }

        // POST: Pizzes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Pizze pizze = db.Pizze.Find(id);
            db.Pizze.Remove(pizze);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

pizzerona/Views/Pizzes/AddPizza.cshtml
@model IEnumerable<pizzerona.Models.Pizze>

@{
    ViewBag.Title = "AddPizza";
}

<h2>AddPizza</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table cardGrande">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.img)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Prezzo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TempoConsegna)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ingredienti)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.img)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Prezzo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TempoConsegna)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Ingredienti)
        </td>

        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.id_Pizza }) |
            @Html.ActionLink("Details", "Details", new { id = item.id_Pizza }) |
            <div>
                <div>

                    <button class="aggiungi-carrello" data-id="@item.id_Pizza">Aggiungi al carrello</button>
                    <form>

                        <input id="Quantita" type="number" name="quantita" value="1" min="1" max="30" class="shadow form-control me-2" style="width: auto;">
                    </form>
                </div>
            </div>
     
            <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
            <script>
        $(document).ready(function () {
        $(".aggiungi-carrello").click(function () {
            var idPizza = $(this).data("id");
            var quantita = $("#Quantita").val()
            $.post("/ORDINEs/AggiungiAlCarrello/", { idPizza: idPizza, quantita: quantita }, function (response) {
                alert(response);
            });
        });
    });
            </script>

        </td>
    </tr>
}

</table>

pizzerona/Views/Pizzes/Create.cshtml
@model pizzerona.Models.Pizze

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create","Pizzes", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
                @Html.AntiForgeryToken()

                <div class="form-horizontal cardGrande p-5">
        <h4>Pizze</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.img, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.img, new { htmlAttributes = new { @class = "form-control" , type="file", required = "required" } })
                @Html.ValidationMessageFor(model => model.img, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prezzo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prezzo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prezzo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TempoConsegna, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TempoConsegna, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TempoConsegna, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ingredienti, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ingredienti, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ingredienti, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

pizzerona/Views/Pizzes/Delete.cshtml
@model pizzerona.Models.Pizze

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pizze</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.img)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.img)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prezzo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prezzo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TempoConsegna)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TempoConsegna)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ingredienti)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ingredienti)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

pizzerona/Views/Pizzes/Details.cshtml
@model pizzerona.Models.Pizze

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Pizze</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.img)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.img)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prezzo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prezzo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TempoConsegna)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TempoConsegna)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ingredienti)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ingredienti)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id_Pizza }) |
    @Html.ActionLink("Back to List", "Index")
</p>

pizzerona/Views/Pizzes/Edit.cshtml
@model pizzerona.Models.Pizze

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pizze</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_Pizza)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.img, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.img, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.img, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prezzo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prezzo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prezzo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TempoConsegna, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TempoConsegna, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TempoConsegna, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ingredienti, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ingredienti, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ingredienti, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

pizzerona/Views/Pizzes/Index.cshtml
@model IEnumerable<pizzerona.Models.Pizze>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div class="row" >
    <img src="~/img/Screenshot 2024-03-12 181453.png"/>
</div>
<div class="card-container cardGrande p-4"> 
    <h1 class="text-center fw-bolder mb-4">\\ Le nostre Pizze //</h1>
    <div class="row g-0">
        @foreach (var item in Model)
        {

            <div class="card mb-3">
                <div class="row g-0">

                    <div class="col-md-8">
                        <div class="card-body">
                            <h2 class="card-title border-bottom">@Html.DisplayFor(modelItem => item.Nome)</h2>
                            <p class="card-text">@Html.DisplayFor(modelItem => item.Prezzo) $</p>
                            <p class="card-text">@Html.DisplayFor(modelItem => item.TempoConsegna)</p>
                            <p class="card-text">@Html.DisplayFor(modelItem => item.Ingredienti)</p>
                            @Html.ActionLink("Edit", "Edit", new { id = item.id_Pizza }, new { @class = "btn btn-primary" })
                            @Html.ActionLink("Details", "Details", new { id = item.id_Pizza }, new { @class = "btn btn-info" })
                            @Html.ActionLink("Delete", "Delete", new { id = item.id_Pizza }, new { @class = "btn btn-danger" })
                            @Html.ActionLink("AddPizza", "AddPizza", new { id = item.id_Pizza }, new { @class = "btn btn-warning" })
                            <a href="@Url.Action("Index", "ORDINEs")">Azione</a>


                        </div>
                    </div>
                    <div class="col-md-4">
                        <img src="@Html.Raw(item.img)" height="220" width="220" class="" alt="...">
                    </div>
                </div>
            </div>
        }
    </div>
</div>